[package]
name = "framework_rgbafan"
version = "0.1.0"
edition = "2024"

[dependencies]
framework_lib = { git = "https://github.com/FrameworkComputer/framework-system.git" }
anyhow = "1.0"
libc = "0.2.178"
rustfft = "6.4.1"
num-complex = "0.4.6"
